/// <reference types="cypress" />

context('Actions', () => {

  // beforeEach(() => {
  //   cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
  // })

  // in order to run these tests login manually as:user=test123@gmail.com pass=123456

  it('clicks on Create an Exercise button', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/sign-in')
    // cy.get('.govuk-grid-column-full > :nth-child(2) > .govuk-button').click()
    // cy.get('.text-right > .govuk-!-margin-right-1').click()
    cy.get('#main-content > div > div:nth-child(1) > div > div > a').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Create an exercise ')
  })

  it('fills out exercise content, submits and saves', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.get('#main-content > div > div:nth-child(1) > div > div > a').click()
    cy.get('#exercise-name').type('Legal exercise test')
    cy.get('#is-more-info-needed__1').click()
    cy.get('#select-more-info__1').click()
    cy.get('#select-more-info__2').click()
    cy.get('#select-more-info__3').click()
    cy.get('#select-more-info__4').click()
    cy.get('#select-more-info__5').click()
    cy.get('#select-more-info__6').click()
    cy.get('#select-more-info__7').click()
    cy.get('#select-more-info__8').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Website listing ')
  })

  it('fills out website listing section', () => {
    cy.get('#estimated-launch-date-month').type('01')
    cy.get('#estimated-launch-date-year').type('2020')
    cy.get('#role-summary').type('Random text')
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Contacts ')
  })

  it('fills out contacts section', () => {
    cy.get('#exercise-mailbox').clear().type('a@judicialappointments.digital')
    cy.get('#senior_selection_exercise_manager_0').type('b@gmail.com')
    cy.get('#selection_exercise_manager_0').type('c@gmail.com')
    cy.get('#selection_exercise_officer_0').type('d@judicialappointments.digital')
    cy.get('#assigned_comissioner_0').type('e@gmail.com')
    // cy.get('#appropriate-authority__16').click()
    cy.get('#hmcts-welshgov-lead').type('f@gmail.com')
    cy.get('#hmcts-welshgov-contact').type('g@gmail.com')
    cy.get('#judicial-office-contact').type('h@gmail.com')
    cy.get('#lead_judge_0').type('i@gmail.com')
    cy.get('#drafting_judge_0').type('j@gmail.com')
    cy.get('#statutory_consultee_0').type('k@gmail.com')
    cy.get(':nth-child(18)').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Shortlisting methods ')
  })

  it('fills out shortlisting methods section', () => {
    cy.get('#shortlisting-methods__16').click()
    cy.get('#shortlisting-methods__17').click()
    cy.get('#shortlisting-methods__18').click()
    cy.get('#shortlisting-methods__19').click()
    cy.get('#shortlisting-methods__20').click()
    cy.get('#shortlisting-methods__21').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Timeline ')
  })

  it('fills out timeline section', () => {
    cy.get('#open-for-applications-day').type('01')
    cy.get('#open-for-applications-month').type('03')
    cy.get('#open-for-applications-year').type('2020')
    cy.get('#closed-for-applications-day').type('01')
    cy.get('#closed-for-applications-month').type('01')
    cy.get('#closed-for-applications-year').type('2099')
    cy.get('#sift-start-date-day').type('01')
    cy.get('#sift-start-date-month').type('01')
    cy.get('#sift-start-date-year').type('2020')
    cy.get('#sift-end-date-day').type('01')
    cy.get('#sift-end-date-month').type('01')
    cy.get('#sift-end-date-year').type('2021')
    cy.get('#name-blind-sift-start-date-day').type('01')
    cy.get('#name-blind-sift-start-date-month').type('01')
    cy.get('#name-blind-sift-start-date-year').type('2020')
    cy.get('#name-blind-sift-end-date-day').type('01')
    cy.get('#name-blind-sift-end-date-month').type('01')
    cy.get('#name-blind-sift-end-date-year').type('2021')
    cy.get('#telephone-assessment-start-date-day').type('01')
    cy.get('#telephone-assessment-start-date-month').type('01')
    cy.get('#telephone-assessment-start-date-year').type('2020')
    cy.get('#telephone-assessment-end-date-day').type('01')
    cy.get('#telephone-assessment-end-date-month').type('01')
    cy.get('#telephone-assessment-end-date-year').type('2021')
    cy.get('#sj-test-date-day').type('01')
    cy.get('#sj-test-date-month').type('10')
    cy.get('#sj-test-date-year').type('2020')
    cy.get('#sj-test-start-time-hour').type('13')
    cy.get('#sj-test-start-time-minute').type('00')
    cy.get('#sj-test-end-time-hour').type('14')
    cy.get('#sj-test-end-time-minute').type('00')
    cy.get('#sj-test-outcome-day').type('01')
    cy.get('#sj-test-outcome-month').type('01')
    cy.get('#sj-test-outcome-year').type('2021')
    cy.wait(500)
    cy.get('#ca-test-date-day').type('01')
    cy.get('#ca-test-date-month').type('04')
    cy.get('#ca-test-date-year').type('2020')
    cy.get('#ca-test-start-time-hour').type('13')
    cy.get('#ca-test-start-time-minute').type('00')
    cy.get('#ca-test-end-time-hour').type('14')
    cy.get('#ca-test-end-time-minute').type('00')
    cy.get('#ca-test-outcome-day').type('01')
    cy.get('#ca-test-outcome-month').type('02')
    cy.get('#ca-test-outcome-year').type('2021')
    cy.get('#scenario-test-date-day').type('01')
    cy.get('#scenario-test-date-month').type('06')
    cy.get('#scenario-test-date-year').type('2020')
    cy.get('#scenario-test-start-time-hour').type('13')
    cy.get('#scenario-test-start-time-minute').type('00')
    cy.get('#scenario-test-end-time-hour').type('14')
    cy.get('#scenario-test-end-time-minute').type('00')
    cy.get('#scenario-test-outcome-day').type('1')
    cy.get('#scenario-test-outcome-month').type('07')
    cy.get('#scenario-test-outcome-year').type('2020')
    cy.get('#shortlisting-outcome-date-month').type('08')
    cy.get('#shortlisting-outcome-date-year').type('2020')
    cy.get('#contact-independent-assessors-day').type('01')
    cy.get('#contact-independent-assessors-month').type('09')
    cy.get('#contact-independent-assessors-year').type('2020')
    cy.get('#independent-assessments-return-date-day').type('01')
    cy.get('#independent-assessments-return-date-month').type('10')
    cy.get('#independent-assessments-return-date-year').type('2020')
    cy.get('#eligibility-scc-date-day').type('01')
    cy.get('#eligibility-scc-date-month').type('10')
    cy.get('#eligibility-scc-date-year').type('2020')
    cy.get('#selection_start_0-day').type('01')
    cy.get('#selection_start_0-month').type('11')
    cy.get('#selection_start_0-year').type('2020')
    cy.get('#selection_end_0-day').type('01')
    cy.get('#selection_end_0-month').type('11')
    cy.get('#selection_end_0-year').type('2020')
    cy.get('#selection_location_0').type('Wherever')
    cy.get('#character-checks-date-day').type('01')
    cy.get('#character-checks-date-month').type('10')
    cy.get('#character-checks-date-year').type('2020')
    cy.get('#statutory-consultation-date-day').type('01')
    cy.get('#statutory-consultation-date-month').type('12')
    cy.get('#statutory-consultation-date-year').type('2020')
    cy.get('#character-and-selection-scc-date-day').type('01')
    cy.get('#character-and-selection-scc-date-month').type('01')
    cy.get('#character-and-selection-scc-date-year').type('2021')
    cy.get('#final-outcome-month').type('06')
    cy.get('#final-outcome-year').type('2021')
    cy.get('#emd-second-stage-start-date-day').type('01')
    cy.get('#emd-second-stage-start-date-month').type('07')
    cy.get('#emd-second-stage-start-date-year').type('2021')
    cy.get('#emd-second-stage-end-date-day').type('01')
    cy.get('#emd-second-stage-end-date-month').type('08')
    cy.get('#emd-second-stage-end-date-year').type('2020')
    cy.get('#emp-scc-date-day').type('01')
    cy.get('#emp-scc-date-month').type('09')
    cy.get('#emp-scc-date-year').type('2020')
    cy.get('#emp-outcome-date-month').type('03')
    cy.get('#emp-outcome-date-year').type('2021')
    cy.wait(500)
    cy.get(':nth-child(39)').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Timeline ')
  })

  // it('fills out exercise content, submits and saves', () => {
  //   cy.get('#type-of-exercise__16').click()
  //   cy.get('#is-court-or-tribunal__20').click()
  //   cy.get('#jurisdiction__25').click()
  //   cy.get('#is-statutory-consultation-waived__23').click()
  //   cy.get('#appointment-type__26').click()
  //   cy.get('#immediate-start').type('1')
  //   cy.get('#future-start').type('1')
  //   cy.get('#location').type('London')
  //
  //
  // })



  // it('fills out vacancy information, submits and saves', () => {
  //   // cy.get('#type-of-exercise__3').click()
  //   // cy.get('#is-court-or-tribunal__7').click()
  //   // cy.get('#jurisdiction__11').click()
  //   // cy.get('#is-statutory-consultation-waived__10').click()
  //   // cy.get('#appointment-type__13').click()
  //   // cy.get('#immediate-start').type('1')
  //   // cy.get('#future-start').type('1')
  //   // cy.get('#future-start').click()
  //   // cy.get('#location').type('Here')
  //   // cy.get('#welsh-requirement__15').click()
  //   // cy.get('#role-summary').type('Something')
  //   // cy.get("#main-content > div > div > form > div > div:nth-child(15) > div.ck.ck-reset.ck-editor.ck-rounded-corners > div.ck.ck-editor__main > div").type('Please work')
  //   // cy.wait(500)
  //   // cy.get('#main-content > div > div > form > div > button').click()
  // })

})
