context('Actions', () => {

  // in order to run these tests login manually as:user=test123@gmail.com pass=123456
  it('Creates an exercise', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/sign-in')
    cy.get('#main-content > div > div:nth-child(1) > div > div > a').click()
    cy.get('.govuk-heading-xl').should('have.text', ' Create an exercise ')
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.get('#main-content > div > div:nth-child(1) > div > div > a').click()
    cy.get('#exercise-name').type('Legal exercise test')
    cy.get('#is-more-info-needed__1').click()
    cy.get('#select-more-info__1').click()
    cy.get('#select-more-info__2').click()
    cy.get('#select-more-info__3').click()
    cy.get('#select-more-info__4').click()
    cy.get('#select-more-info__5').click()
    cy.get('#select-more-info__6').click()
    cy.get('#select-more-info__7').click()
    cy.get('#select-more-info__8').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()

    // storedURL = cy.url()
  })

  it('fills out website listing section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(1) > .govuk-table__header > .govuk-link').click()
    cy.get('#exercise-name').clear().type('Legal exercise test')
    cy.get('#estimated-launch-date-month').clear().type('02')
    cy.get('#estimated-launch-date-year').clear().type('2020')
    cy.get('#role-summary').clear().type('Test role')
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('#exercise-edit-summary-completed').should('be.visible')
  })

  it('fills out vacancy information, submits and saves', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(2) > .govuk-table__header > .govuk-link').click()
    cy.get('#type-of-exercise__1').click()
    cy.get('#is-court-or-tribunal__5').click()
    cy.get('#jurisdiction__2').click()
    cy.get('#is-statutory-consultation-waived__8').click()
    cy.get('#appointment-type__11').click()
    cy.get('#immediate-start').type('1')
    cy.get('#future-start').type('1')
    cy.get('#location').type('Here')
    cy.get('#welsh-requirement__13').click()
    cy.get('#role-summary').clear().type('Something')
    cy.get("#main-content > div > div > form > div > div:nth-child(15) > div.ck.ck-reset.ck-editor.ck-rounded-corners > div.ck.ck-editor__main > div").clear().type('Please work')
    cy.wait(500)
    cy.get('#main-content > div > div > form > div > button').click()
    cy.get('#exercise-edit-vacancy-completed').should('be.visible')
  })

  it('fills out contacts section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(3) > .govuk-table__header > .govuk-link').click()
    cy.get('#exercise-mailbox').clear().type('a@judicialappointments.digital')
    cy.get('#senior_selection_exercise_manager_0').clear().type('b@gmail.com')
    cy.get('#selection_exercise_manager_0').clear().type('c@gmail.com')
    cy.get('#selection_exercise_officer_0').clear().type('d@judicialappointments.digital')
    cy.get('#assigned_comissioner_0').clear().type('e@gmail.com')
    // cy.get('#appropriate-authority__16').click()
    cy.get('#hmcts-welshgov-lead').clear().type('f@gmail.com')
    cy.get('#hmcts-welshgov-contact').clear().type('g@gmail.com')
    cy.get('#judicial-office-contact').clear().type('h@gmail.com')
    cy.get('#lead_judge_0').clear().type('i@gmail.com')
    cy.get('#drafting_judge_0').clear().type('j@gmail.com')
    cy.get('#statutory_consultee_0').clear().type('k@gmail.com')
    cy.get(':nth-child(18)').click()
    cy.get('#exercise-edit-contacts-completed').should('be.visible')
  })

  it('fills out timeline section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(4) > .govuk-table__header > .govuk-link').click()
    cy.get('#open-for-applications-day').clear().type('01')
    cy.get('#open-for-applications-month').clear().type('03')
    cy.get('#open-for-applications-year').clear().type('2020')
    cy.get('#closed-for-applications-day').clear().type('01')
    cy.get('#closed-for-applications-month').clear().type('01')
    cy.get('#closed-for-applications-year').clear().type('2099')
    cy.get('#sift-start-date-day').clear().type('01')
    cy.get('#sift-start-date-month').clear().type('01')
    cy.get('#sift-start-date-year').clear().type('2020')
    cy.get('#sift-end-date-day').clear().type('01')
    cy.get('#sift-end-date-month').clear().type('01')
    cy.get('#sift-end-date-year').clear().type('2021')
    cy.get('#name-blind-sift-start-date-day').clear().type('01')
    cy.get('#name-blind-sift-start-date-month').clear().type('01')
    cy.get('#name-blind-sift-start-date-year').clear().type('2020')
    cy.get('#name-blind-sift-end-date-day').clear().type('01')
    cy.get('#name-blind-sift-end-date-month').clear().type('01')
    cy.get('#name-blind-sift-end-date-year').clear().type('2021')
    cy.get('#telephone-assessment-start-date-day').clear().type('01')
    cy.get('#telephone-assessment-start-date-month').clear().type('01')
    cy.get('#telephone-assessment-start-date-year').clear().type('2020')
    cy.get('#telephone-assessment-end-date-day').clear().type('01')
    cy.get('#telephone-assessment-end-date-month').clear().type('01')
    cy.get('#telephone-assessment-end-date-year').clear().type('2021')
    cy.get('#sj-test-date-day').clear().type('01')
    cy.get('#sj-test-date-month').clear().type('10')
    cy.get('#sj-test-date-year').clear().type('2020')
    cy.get('#sj-test-start-time-hour').clear().type('13')
    cy.get('#sj-test-start-time-minute').clear().type('00')
    cy.get('#sj-test-end-time-hour').clear().type('14')
    cy.get('#sj-test-end-time-minute').clear().type('00')
    cy.get('#sj-test-outcome-day').clear().type('01')
    cy.get('#sj-test-outcome-month').clear().type('01')
    cy.get('#sj-test-outcome-year').clear().type('2021')
    cy.get('#ca-test-date-day').clear().type('01')
    cy.get('#ca-test-date-month').clear().type('04')
    cy.get('#ca-test-date-year').clear().type('2020')
    cy.get('#ca-test-start-time-hour').clear().type('13')
    cy.get('#ca-test-start-time-minute').clear().type('00')
    cy.get('#ca-test-end-time-hour').clear().type('14')
    cy.get('#ca-test-end-time-minute').clear().type('00')
    cy.get('#ca-test-outcome-day').clear().type('01')
    cy.get('#ca-test-outcome-month').clear().type('02')
    cy.get('#ca-test-outcome-year').clear().type('2021')
    cy.get('#scenario-test-date-day').clear().type('01')
    cy.get('#scenario-test-date-month').clear().type('06')
    cy.get('#scenario-test-date-year').clear().type('2020')
    cy.get('#scenario-test-start-time-hour').clear().type('13')
    cy.get('#scenario-test-start-time-minute').clear().type('00')
    cy.get('#scenario-test-end-time-hour').clear().type('14')
    cy.get('#scenario-test-end-time-minute').clear().type('00')
    cy.get('#scenario-test-outcome-day').clear().type('1')
    cy.get('#scenario-test-outcome-month').clear().type('07')
    cy.get('#scenario-test-outcome-year').clear().type('2020')
    cy.get('#shortlisting-outcome-date-month').clear().type('08')
    cy.get('#shortlisting-outcome-date-year').clear().type('2020')
    cy.get('#contact-independent-assessors-day').clear().type('01')
    cy.get('#contact-independent-assessors-month').clear().type('09')
    cy.get('#contact-independent-assessors-year').clear().type('2020')
    cy.get('#independent-assessments-return-date-day').clear().type('01')
    cy.get('#independent-assessments-return-date-month').clear().type('10')
    cy.get('#independent-assessments-return-date-year').clear().type('2020')
    cy.get('#eligibility-scc-date-day').clear().type('01')
    cy.get('#eligibility-scc-date-month').clear().type('10')
    cy.get('#eligibility-scc-date-year').clear().type('2020')
    cy.get('#selection_start_0-day').clear().type('01')
    cy.get('#selection_start_0-month').clear().type('11')
    cy.get('#selection_start_0-year').clear().type('2020')
    cy.get('#selection_end_0-day').clear().type('01')
    cy.get('#selection_end_0-month').clear().type('11')
    cy.get('#selection_end_0-year').clear().type('2020')
    cy.get('#selection_location_0').clear().type('Wherever')
    cy.get('#character-checks-date-day').clear().type('01')
    cy.get('#character-checks-date-month').clear().type('10')
    cy.get('#character-checks-date-year').clear().type('2020')
    cy.get('#statutory-consultation-date-day').clear().type('01')
    cy.get('#statutory-consultation-date-month').clear().type('12')
    cy.get('#statutory-consultation-date-year').clear().type('2020')
    cy.get('#character-and-selection-scc-date-day').clear().type('01')
    cy.get('#character-and-selection-scc-date-month').clear().type('01')
    cy.get('#character-and-selection-scc-date-year').clear().type('2021')
    cy.get('#final-outcome-month').clear().type('06')
    cy.get('#final-outcome-year').clear().type('2021')
    cy.get('#emd-second-stage-start-date-day').clear().type('01')
    cy.get('#emd-second-stage-start-date-month').clear().type('07')
    cy.get('#emd-second-stage-start-date-year').clear().type('2021')
    cy.get('#emd-second-stage-end-date-day').clear().type('01')
    cy.get('#emd-second-stage-end-date-month').clear().type('08')
    cy.get('#emd-second-stage-end-date-year').clear().type('2020')
    cy.get('#emp-scc-date-day').clear().type('01')
    cy.get('#emp-scc-date-month').clear().type('09')
    cy.get('#emp-scc-date-year').clear().type('2020')
    cy.get('#emp-outcome-date-month').clear().type('03')
    cy.get('#emp-outcome-date-year').clear().type('2021')
    cy.wait(1000)
    cy.get(':nth-child(39)').click()
    cy.get('#exercise-edit-shortlisting-completed').should('be.visible')
  })

  it('fills out shortlisting methods section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(5) > .govuk-table__header > .govuk-link').click()
    cy.get('#shortlisting-methods__1').uncheck().click()
    cy.get('#shortlisting-methods__2').uncheck().click()
    cy.get('#shortlisting-methods__3').uncheck().click()
    cy.get('#shortlisting-methods__4').uncheck().click()
    cy.get('#shortlisting-methods__5').uncheck().click()
    cy.get('#shortlisting-methods__6').uncheck().click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('#exercise-edit-shortlisting-completed').should('be.visible')
  })

  it('fills out eligibility information section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(6) > .govuk-table__header > .govuk-link').click()
    cy.get('#post-qualification-experience__1').click()
    cy.get('#authorisations__1').uncheck().click()
    cy.get('#additional-selection-criteria-apply__5').click()
    cy.get('#previous-judicial-experience-apply__6').click()
    cy.get('#qualifications__4').uncheck().click()
    cy.get('#reasonable-length-service__8').click()
    cy.get('#retirement-age__12').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('#exercise-edit-eligibility-completed').should('be.visible')
  })

  it('fills out working preferences section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(7) > .govuk-table__header > .govuk-link').click()
    cy.get('#exercise-location-question').clear().type('Question 1')
    cy.get('#exercise-location-question-type__1').click()
    cy.get('#answer_location_0').clear().type('Answer 1')
    cy.get('#exercise-jurisdiction-question').clear().type('Question 2')
    cy.get('#exercise-jurisdiction-question-type__4').click()
    cy.get('#answer_jurisdiction_0').clear().type('Answer 2')
    cy.get('.govuk-grid-column-two-thirds > :nth-child(5)').click()
    cy.get('#exercise-edit-working-preferences-completed').should('be.visible')
  })

  it('fills out assessment options section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(8) > .govuk-table__header > .govuk-link').click()
    cy.get('#shortlisting-methods__7').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('#exercise-edit-assessment-options-completed').should('be.visible')
  })

  it('fills out exercise downloads section', () => {
    cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
    cy.contains('Legal exercise test').click()
    cy.get(':nth-child(9) > .govuk-table__header > .govuk-link').click()
    cy.get('.govuk-grid-column-two-thirds > .govuk-button').click()
    cy.get('#exercise-edit-downloads-completed').should('be.visible')
  })

  // it('Clicks on send for approval', () => {
  //   cy.visit('https://admin-staging.judicialappointments.digital/dashboard')
  //   cy.contains('Legal exercise test').click()
  //   cy.get('.govuk-grid-column-three-quarters > :nth-child(1) > :nth-child(4) > :nth-child(2)').click()
  // })
})
