name: Scheduled actions
on:
  schedule:
    - cron: "* * * * *"

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependency Checkb
        run: npm audit --omit=dev
