name: Scheduled actions
on:
  schedule:
    - cron: "* * * * *"

jobs:
  dependency_check:
    name: Dependency Check
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    run: npm audit --omit=dev
